cc/cc/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('medico.urls')),
]

cc/medico/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('consultations/<int:consultationID>/',views.consultationDetail, name='consultationDetail' ),
    path('consultations/', views.consultations, name='listeconsultations'),
    path('nouvelle_consultation/', views.nouvelle_consultation, name='nouvelle_consultation'),
    path('effacer_consultation/<int:consultationID>/', views.deleteconsultation, name='deleteconsultation'),
    path('changer_consultation/<int:consultationID>/',views.editConsultation, name='editConsultation' ),
    
    path('modifier_traitement/<int:traitementID>', views.traitementModif, name='modifier_traitement'),
    path('traitement/<int:traitementID>/', views.traitementdetails, name='traitementdetails'),

    path('', views.main, name='main'), # URL pour la page principale
    path('ajouter_traitement/<int:consultation_id>/', views.ajouter_traitement, name='ajouter_traitement'),
    path('traitements/',views.traitements, name='listetraitements'),

    path('delete_traitement/<int:traitementID>/', views.delete_traitement, name='delete_traitement'), # URL pour supprimer un traitement
    path('consultation/<int:consultationID>/traitements/', views.suppression_traitement, name='suppression_traitement'), # URL page suppression traitements d'une consultation

    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'), 
    path('add_doctor/', views.add_doctor, name='add_doctor'),
    path('appointments/', views.liste_rendez_vous, name='liste_rendez_vous'),
    path('takeappointments/', views.prendre_rendez_vous, name='prendre_rendez_vous'),
    path('doctors/', views.listdoctors, name='doctors'),
    path('editDoctor/<int:doctorID>', views.editDoctor, name='editDoctor'),
    path('deleteDoctor/<int:doctorID>', views.deleteDoctor, name='deleteDoctor'),
]

cc/medico/models.py
from django.db import models
from django.contrib.auth.hashers import make_password, check_password
from django.utils import timezone

# Create your models here.
class Consultation(models.Model):
    GENRE_CHOIX = [('F', "Femme"), ('H', "Homme")]
    patient_nom = models.CharField(max_length=40, null=False)
    patient_prenom = models.CharField(max_length=30, null=False)
    patient_genre = models.CharField(max_length=1, null=False, choices=GENRE_CHOIX)
    patient_age = models.IntegerField(null=False)
    description = models.TextField(null=False)
    date_consultation = models.DateField(null=False)

def __str__(self):
    return self.patient_nom

class Traitement(models.Model):
    medicament=models.CharField(max_length=40, null=False)
    quantite=models.IntegerField(null=False)
    contenant=models.CharField(max_length=20, null=False)
    duree=models.IntegerField(null=False)  # durée en jours
    effects_secondaires=models.TextField(null=False, blank=True)
    consultation=models.ForeignKey(Consultation, on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.medicament

class Doctor(models.Model):
    SPECIALITY_CHOICES = [
        ('Gynécologue', 'Gynécologue'),
        ('Médecin généraliste', 'Médecin généraliste'),
        ('Cardiologue', 'Cardiologue'),
        ('Pédiatre', 'Pédiatre'),
        ('Dermatologue', 'Dermatologue'),
        ('Ophtalmologue', 'Ophtalmologue'),
        ('Orthopédiste', 'Orthopédiste'),
        ('Neurologue', 'Neurologue'),
        ('Psychiatre', 'Psychiatre'),
        ('Radiologue', 'Radiologue'),
        ('Chirurgien', 'Chirurgien'),
        ('Gastro-entérologue', 'Gastro-entérologue'),
        ('Rhumatologue', 'Rhumatologue'),
        ('Endocrinologue', 'Endocrinologue'),
        ('Urologue', 'Urologue'),
        ('Hématologue', 'Hématologue'),
        ('Infectiologue', 'Infectiologue'),
    ]
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    speciality = models.CharField(max_length=50, choices=SPECIALITY_CHOICES)
    password = models.CharField(max_length=100, default="D000000")
    shift = models.CharField(max_length=10)
    start_time = models.CharField(max_length=5, blank=True)
    end_time = models.CharField(max_length=5, blank=True)
    available_days = models.TextField(blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name} - {self.speciality}"

    def set_password(self, raw_password):
        self.password = make_password(raw_password)

    def check_password(self, raw_password):
        return check_password(raw_password, self.password)

    def save(self, *args, **kwargs):
        if not self.pk:
            if self.password == "D000000":
                self.set_password(self.password)
        super(Doctor, self).save(*args, **kwargs)

class Patient(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=128)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def set_password(self, raw_password):
        self.password = make_password(raw_password)

    def check_password(self, raw_password):
        return check_password(raw_password, self.password)

    def save(self, *args, **kwargs):
        if not self.pk or not self.password.startswith('pbkdf2_'):
            self.set_password(self.password)
        super().save(*args, **kwargs)

class Appointment(models.Model):
    doctor = models.ForeignKey('Doctor', on_delete=models.CASCADE, related_name='appointments')
    patient = models.ForeignKey('Patient', on_delete=models.CASCADE, related_name='appointments')
    appointment_date = models.DateField()
    appointment_time = models.TimeField()
    reason = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"({self.appointment_date} {self.appointment_time})"

cc/medico/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import ConsultationForm,TraitementForm,DoctorForm, AppointmentForm
from .models import Consultation,Traitement,Doctor,Patient,Appointment
from django.contrib import messages
from datetime import datetime

def about(request):
    return render(request, 'medico/about.html')

def checkpermissions(request):
    if not (request.session.get('is_doctor') or request.session.get('is_admin')):
        return redirect('about')

def consultationDetail(request, consultationID):
    permission = checkpermissions(request)
    if permission:
        return permission
    consultation=Consultation.objects.get(pk=consultationID)
    lesTraitements = consultation.traitement_set.all()
    context = {
        "consultation": consultation,
        "lesTraitements": lesTraitements,
    }
    return render(request,"medico/consultationDetails.html",context)

def consultations(request):
    permission = checkpermissions(request)
    if permission:
        return permission
    lesConsultations = Consultation.objects.all().order_by('patient_nom')
    return render(request, 'medico/listeconsultations.html', {"lesConsultations":lesConsultations})

def nouvelle_consultation(request):
    permission = checkpermissions(request)
    if permission:
        return permission
    if request.method == 'POST':
        form = ConsultationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listeconsultations')  
    else:
        form = ConsultationForm()

    return render(request, 'medico/nouvelle_consultation.html', {'form': form})

def deleteconsultation(request, consultationID):
    permission = checkpermissions(request)
    if permission:
        return permission
    consultation = get_object_or_404(Consultation, pk=consultationID)

    if request.method == 'POST':
        consultation.delete()
        return redirect('listeconsultations')

    return render(request, "medico/consultationSupprConfirm.html", {"consultationid":consultationID})

def check_save(form,request):
    permission = checkpermissions(request)
    if permission:
        return permission
    if form.is_valid():
        consultation=form.save(commit=False)
        consultation.save()
    return consultation.id


def editConsultation(request,consultationID):
    permission = checkpermissions(request)
    if permission:
        return permission
    consultation = get_object_or_404(Consultation,pk=consultationID)
    if request.method =="POST":
        form = ConsultationForm(request.POST,instance=consultation)
        id=check_save(form,request)
        return redirect("consultationDetail",consultationID=id)
    else:
        form=ConsultationForm(instance=consultation)
    return render(
        request,"medico/consultationModif.html",{"form": form, "button_label": "modifier"},
    ) 

def traitementModif(request, traitementID):
    permission = checkpermissions(request)
    if permission:
        return permission
    traitement = get_object_or_404(Traitement, pk=traitementID)
    if(request.method == 'POST'):
        form = TraitementForm(request.POST,instance=traitement)
        traitementid = check_save(form, request)
        return redirect('traitementdetails', traitementID=traitementid)
    else:
        form=TraitementForm(instance=traitement)
    
    return render(request, "medico/traitementModif.html", {"form":form, "button_label":"modifier"})


def traitementdetails(request, traitementID):
    permission = checkpermissions(request)
    if permission:
        return permission
    traitement = get_object_or_404(Traitement, pk=traitementID)
    return render(request, 'medico/traitementdetails.html', {"traitement":traitement})


def main(request): # Vue pour la page principale
    return render(request, 'medico/main.html')

def ajouter_traitement(request, consultation_id):
    permission = checkpermissions(request)
    if permission:
        return permission
    consultation = Consultation.objects.get(pk=consultation_id)


    if request.method == 'POST':
        form = TraitementForm(request.POST)
        if form.is_valid():
            traitement = form.save(commit=False)
            traitement.consultation = consultation #clé etrangere consultation
            traitement.save()
            return redirect('consultationDetail', consultationID=consultation.id)
    else:
        form = TraitementForm()


    return render(request, 'medico/ajouter_traitement.html', {'form': form, 'consultation': consultation})


def traitements(request):
    permission = checkpermissions(request)
    if permission:
        return permission
    lesTraitements = Traitement.objects.all().order_by('medicament')
    return render(request, 'medico/listetraitement.html', {"lesTraitements":lesTraitements})


def suppression_traitement(request, consultationID): # Vue pour la page de suppression des traitements d'une consultation
    permission = checkpermissions(request)
    if permission:
        return permission
    consultation = get_object_or_404(Consultation, pk=consultationID)
    traitements = consultation.traitement_set.all()
    return render(request, "medico/suppression_traitement.html",{"consultation": consultation, 
                                                                          "traitements": traitements})
                                                                          


def delete_traitement(request, traitementID): # Vue pour supprimer un traitement
    permission = checkpermissions(request)
    if permission:
        return permission
    traitement = get_object_or_404(Traitement, pk=traitementID)
    consultation_id = traitement.consultation.id

    if request.method == 'POST':
        traitement.delete()
        return redirect('suppression_traitement', consultationID=consultation_id)

    return render(request, "medico/traitementSupprConfirm.html", {"traitementID":traitementID})

ADMIN_CREDENTIALS = {
    'username': 'admin',
    'password': 'admin/check'
}

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if username == ADMIN_CREDENTIALS['username'] and password == ADMIN_CREDENTIALS['password']:
            request.session['is_admin'] = True
            request.session['is_doctor'] = False
            return redirect('about')
        try:
            doctor = Doctor.objects.get(first_name=username)
            if doctor.check_password(password):
                request.session['is_doctor'] = True
                request.session['is_admin'] = False
                request.session['is_patient'] = False
                request.session['doctor_id'] = doctor.id
                return redirect('about')
            else:
                messages.error(request, 'Mot de passe incorrect.')
                return redirect('login')
        except Doctor.DoesNotExist:
            pass
        try:
            patient = Patient.objects.get(email=username)
            if patient.check_password(password):
                request.session['is_patient'] = True
                request.session['is_doctor'] = False
                request.session['is_admin'] = False
                request.session['patient_email'] = patient.email
                return redirect('about')
            else:
                messages.error(request, 'Mot de passe incorrect.')
                return redirect('login')
        except Patient.DoesNotExist:
            messages.error(request, "Nom d'utilisateur ou email incorrect.")

    return render(request, 'medico/login.html')

def logout_view(request):
    request.session.flush() 
    return redirect('about')

def add_doctor(request):
    permission = checkpermissions(request)
    if permission:
        return permission
    if request.method == 'POST':
        form = DoctorForm(request.POST)
        if form.is_valid():

            doctor = form.save()
            if doctor.shift == 'morning':
                doctor.start_time = '08:00'
                doctor.end_time = '17:00'
            elif doctor.shift == 'night':
                doctor.start_time = '17:00'
                doctor.end_time = '08:00'

            doctor.save()
            doctor.available_days = ', '.join(form.cleaned_data['available_days'])
            doctor.save()

            messages.success(request, "Médecin ajouté avec succès!")
            return redirect('about')  

    else:
        form = DoctorForm()

    return render(request, 'medico/add_doctor.html', {'form': form})

def register_view(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')

        if password != confirm_password:
            messages.error(request, "Les mots de passe ne correspondent pas.")
            return redirect('register')

        if Patient.objects.filter(email=email).exists():
            messages.error(request, "Un compte avec cet email existe déjà.")
            return redirect('register')

        patient = Patient(
            first_name=first_name,
            last_name=last_name,
            email=email,
            password=password,
        )
        patient.save()
        messages.success(request, "Compte créé avec succès. Connectez-vous maintenant.")
        return redirect('login')

    return render(request, 'medico/register.html')

def prendre_rendez_vous(request):
    if not request.session.get('is_patient'):
        messages.error(request, "Vous devez être connecté comme patient pour prendre un rendez-vous.")
        return redirect('login')
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            appointment = form.save(commit=False)

cc/medico/templates/medico/about.html
{% extends 'medico/main.html' %}
{% load django_bootstrap5 %}
{% block content %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Medico{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <header class="text-center mb-4">
            <h1>À propos de Medico</h1>
            <p class="lead">Révolutionner l'expérience des consultations médicales en ligne.</p>
        </header>

        <section>
            <h2>Notre Mission</h2>
            <p>Chez Medico, notre mission est de révolutionner l'expérience de soins de santé en offrant aux médecins une plateforme puissante pour mener des consultations en ligne, gérer les données des patients et améliorer la qualité des soins.</p>
        </section>

        <section class="mt-4">
            <h2>Pourquoi Choisir Medico ?</h2>
            <ul>
                <li><strong>Consultations Faciles :</strong> Planifiez, gérez et effectuez des consultations virtuelles en toute simplicité.</li>
                <li><strong>Données Patients Sécurisées :</strong> Notre plateforme garantit que toutes les données des patients sont cryptées et stockées de manière sécurisée.</li>
                <li><strong>Gestion Efficace des Rendez-vous :</strong> Optimisez la gestion des rendez-vous de votre cabinet avec des rappels automatisés et réduisez les absences.</li>
                <li><strong>Tableau de Bord Complet :</strong> Suivez l'activité de votre pratique grâce à des analyses en temps réel et des informations détaillées sur vos patients.</li>
            </ul>
        </section>

        <section class="mt-5">
            <h2>Contactez-Nous</h2>
            <p>Si vous avez des questions ou souhaitez en savoir plus sur la manière dont Medico peut aider votre pratique, n'hésitez pas à nous contacter :</p>
            <ul>
                <li>Email : support@medico.fr</li>
            </ul>
        </section>
    </div>
</body>
</html>
{% endblock %}

cc/medico/templates/medico/ajouter_traitement.html
{% extends 'medico/main.html'%}
{% load django_bootstrap5 %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
   
</head>
<body>
    <h1 class="display-1">Ajout Traitement</h1>
    <form method="post" class="card p-4 shadow-sm">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Ajouter traitement</button>
</form>
<p>
    <a href="{% url 'listeconsultations'   %}"> Retour à la liste</a>
</p>


</body>
</html>
{% endblock %}

cc/medico/templates/medico/consultationDetails.html
{% extends 'medico/main.html'%}
{% load django_bootstrap5 %}
{% block content %}

    <title>{%block title%}Consultation{%endblock%} </title>
</head>
<body>
    <nav>

          
        </div>
    </nav>
   <h1 class="display-1">Détail de la consultation numero {{ consultation.pk }}</h1>
<ul class="list-group" >
    <li class="list-group-item"><strong>Nom :</strong> {{ consultation.patient_nom }}</li>
    <li class="list-group-item"><strong>Prénom :</strong> {{ consultation.patient_prenom }}</li>
    <li class="list-group-item"><strong>Genre :</strong> {{ consultation.get_patient_genre_display }}</li>
    <li class="list-group-item"><strong>Age :</strong> {{ consultation.patient_age }}</li>
    <li class="list-group-item"><strong>Date :</strong> {{ consultation.date_consultation }}</li>
    <li class="list-group-item"><strong>Description :</strong> {{ consultation.description }}</li>
</ul>
<br>
   
<h1 class="display-1">Les Traitements </h1>
<div class="custom-table">
{% if lesTraitements %}
<table class="table table-striped table-bordered">
    <thead class="table-dark">
        <tr>            
            <th>Medicament</th>
            <th>Quantite</th>
            <th>Contenantt</th>
            <th>Duree en jour</th>
            <th>Effect secondaires</th>
            <th>Consultation</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for unTraitement in lesTraitements %}
        <tr>
        <td>{{unTraitement.medicament}}</td>
        <td>{{unTraitement.quantite}}</td>
        <td>{{unTraitement.contenant}}</td>
        <td>{{unTraitement.duree}}</td>
        <td>{{unTraitement.effects_secondaires}}</td>
        <td>{{ unTraitement.consultation.id }}</td>
        <td><a class="btn btn-sm btn-danger" href="{% url 'delete_traitement' unTraitement.id %}">Supprimer</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% else %}
<p>Aucunes Traitements.</p>
{% endif %}



 <a href="{% url 'editConsultation' consultation.id %}" class="btn btn-sm btn-warning mb-4">
        Modifier Consultation
    </a>
    <br>
    <a href="{% url 'ajouter_traitement' consultation.pk %}" class="btn btn-success mb-4">
        Ajouter un traitement
    </a>


{% endblock %}

cc/medico/templates/medico/consultationModif.html
{% extends 'medico/main.html'%}
{% load django_bootstrap5 %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <h1 class="display-1">Modification de la Consultation {{ consultation.pk }} </h1>
     <form method="post" class="card p-4 shadow-sm">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Ajouter Consultation</button>
    </form>
    
</body>
</html>
{% endblock %}

cc/medico/templates/medico/consultationSupprConfirm.html
{% extends 'medico/main.html'%}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Confirmation de Suppression{% endblock %}</title>
</head>
<body>  
    {% block content %}
    <div class="d-flex justify-content-center mt-5 text-center">
        <div>
            <p>Confirmez la suppression de la consultation numéro : {{ consultationid }}</p>
            <form action="{% url 'deleteconsultation' consultationid %}" method="post">
            {% csrf_token %}
            <button class="btn btn-danger btn-sm" type="submit">Confirmer</button>
        </form>
    </div>
</div>
</body>
</html>
{% endblock %}

cc/medico/templates/medico/listeconsultations.html
{% extends 'medico/main.html'%}
{% load django_bootstrap5 %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Liste Consultations{% endblock %}</title>
</head>

<body>
    
{% if lesConsultations %}
<table class="table table-striped table-bordered">
    <thead class="table-dark">
        <tr>
            <th>Nom Patient</th>
            <th>Prénom Patient</th>
            <th>Genre Patient</th>
            <th>Age Patient</th>
            <th>Description</th>
            <th>Date</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for uneConsultation in lesConsultations %}
        <tr>
        <td>{{uneConsultation.patient_nom}}</td>
        <td>{{uneConsultation.patient_prenom}}</td>
        <td>{{uneConsultation.patient_genre}}</td>
        <td>{{uneConsultation.patient_age}}</td>
        <td>{{uneConsultation.description|slice:":20"}}</td>
        <td>{{ uneConsultation.date_consultation|date:"l j F Y" }}</td>
        <td class="text-center align-middle"><div class="btn-group btn-group-sm" role="group"><a class="btn btn-primary btn-sm" href="{% url 'consultationDetail' uneConsultation.id %}">Détails</a>
        <a class="btn btn-danger btn-sm" href="{% url 'deleteconsultation' uneConsultation.id %}">Effacer</a>
        <a class="btn btn-warning btn-sm" href="{% url 'editConsultation' uneConsultation.id %}" >Modifier</a>
        <a class="btn btn-primary btn-sm" href="{% url 'ajouter_traitement' uneConsultation.id %}">[+]Traitement</a>
        <a class="btn btn-info btn-sm" href="{% url 'suppression_traitement' uneConsultation.id %}">[-]Traitement</a></div></td>
    </tr>
        {% endfor %}
    </tbody>
</table>

{% else %}
<p>Aucunes Consultations.</p>
{% endif %}
</body>
</html>
{% endblock %}

cc/medico/templates/medico/listerendezvous.html
{% extends 'medico/main.html' %}
{% load django_bootstrap5 %}
{%block title%}Rendez-vous{%endblock%}
{% block content %}
<body class="bg-light">

    <div class="container mt-5 mb-5">
        <div class="card shadow-sm">
            <div class="card-body">

                {% if request.session.is_doctor %}
                    <h2 class="text-center mb-4 text-primary">
                        Planning du Dr. 
                        {% if appointments %}
                            {{ appointments.first.doctor.last_name }}
                        {% endif %}
                    </h2>
                {% else %}
                    <h2 class="text-center mb-4 text-primary">Mes Rendez-vous</h2>
                {% endif %}

                {% if appointments %}
                    <div class="table-responsive">
                        <table class="table table-striped table-hover align-middle">
                            <thead class="table-primary">
                                <tr>
                                    {% if request.session.is_doctor %}
                                        <th>Patient</th>
                                    {% else %}
                                        <th>Docteur</th>
                                    {% endif %}
                                    <th>Date</th>
                                    <th>Heure</th>
                                    <th>Raison</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for appt in appointments %}
                                    <tr>
                                        {% if request.session.is_doctor %}
                                            <td>{{ appt.patient.first_name }} {{ appt.patient.last_name }}</td>
                                        {% else %}
                                            <td>{{ appt.doctor.first_name }} {{ appt.doctor.last_name }}</td>
                                        {% endif %}
                                        <td>{{ appt.appointment_date }}</td>
                                        <td>{{ appt.appointment_time }}</td>
                                        <td>{{ appt.reason|default:"—" }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <div class="alert alert-info text-center mt-4">
                        Aucun rendez-vous trouvé.
                    </div>
                {% endif %}

                <div class="text-center mt-4">
                    <a href="{% url 'about' %}" class="btn btn-primary">
                        Retour
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

cc/medico/templates/medico/listetraitement.html
{% extends 'medico/main.html'%}
{% load django_bootstrap5 %}

   {%block title%}Liste Traitements{%endblock%}

{% block content %}


<body>

<div class="custom-table">
    {% if lesTraitements %}
<table class="table table-striped table-bordered">
    <thead class="table-dark">
        <tr>            
            <th>Medicament</th>
            <th>Quantite</th>
            <th>Contenantt</th>
            <th>Duree en jour</th>
            <th>Effect secondaires</th>
            <th>Consultation</th>
            <th>Modifier</th>
            <th>Supprimer</th>
            
        </tr>
    </thead>
    <tbody>
        {% for unTraitement in lesTraitements %}
        <tr>
        <td>{{unTraitement.medicament}}</td>
        <td>{{unTraitement.quantite}}</td>
        <td>{{unTraitement.contenant}}</td>
        <td>{{unTraitement.duree}}</td>
        <td>{{unTraitement.effects_secondaires}}</td>
        <td><a class="btn btn-sm btn-primary" href="{% url 'consultationDetail' unTraitement.consultation.id %}">Consultation details</a></td>
        <td><a class="btn btn-sm btn-warning" href="{% url 'modifier_traitement' unTraitement.id %}">Modifier</a></td>
        <td><a class="btn btn-sm btn-danger" href="{% url 'delete_traitement' unTraitement.id %}">Supprimer</a></td>

        
       
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% else %}
<p>Aucunes Traitements.</p>
{% endif %}

    
</body>
{% endblock %}

cc/medico/templates/medico/login.html
{% extends 'medico/main.html' %}
{% load django_bootstrap5 %}
{% block content %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Connexion</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h2>Se connecter</h2>
        
        {% if messages %}
            <div class="alert alert-danger">
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Nom d'utilisateur ou mail :</label>
                <input type="text" class="form-control" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">Mot de passe:</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <button type="submit" class="btn btn-primary">Se connecter</button>
        </form>
        <p>Pas encore inscrit ? 
    <a href="{% url 'register' %}">Créer un compte</a>
</p>
    </div>
</body>
</html>
{% endblock %}

cc/medico/templates/medico/prendre_rendez_vous.html
{% extends 'medico/main.html' %}
{% load django_bootstrap5 %}
{%block title%}Prendre rendez-vous{%endblock%}
{% block content %}
<h2>Prendre un rendez-vous</h2>

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-success">Confirmer le rendez-vous</button>
</form>

<a href="{% url 'about' %}">Retour</a>

{% endblock %}